### PR TITLE
updated requirements file

### PR DESCRIPTION
**Pull request by VictorGillioz**
Updated requirements file to install the environment dependencies using pip

### CODE REVIEW

**Review by IvanPombo — COMMENTED** [review]
Does this already fix the problem you were having?

**Comment by VictorGillioz** [comment]
The error in checks is known, and caused by the torch-scatter package. This can be solved by a sequential installation of the packages.

**Comment by VictorGillioz** [comment]
> Does this already fix the problem you were having?



> Does this already fix the problem you were having?

No unfortunately not

**Comment by VictorGillioz** [comment]
The latest commit fixes the requirements errors!

**Pull request merged**
