### PR TITLE
added mlflow callbacks for checkpoint artifacts

### PR DESCRIPTION
**Pull request by VictorGillioz**
Added two loggers for MLFlow: The first one logs checkpoints as MLFlow artifacts each time a new checkpoint is saved. The second one logs all the checkpoints saved at the end of trainging.

### CODE REVIEW

**Comment by AugustoPeres** [comment]
I have a high level comment here.

Since we are inheriting from the `mlflow logger` callback and then writing a lot of new code why not just create our own callback to log the models?

In other words, what does this gain when compared to something from scratch [like this](https://github.com/inductiva/inductiva-ml-codebase/pull/8).

Also, in the callback, I am not seeing an option to give it a directory where the models are saved. Is this an argument of the parent class? I am asking because, usually when training on a ray cluster we need all workers to have some common directory that can write to. Then this directory is given to the callbacks, this ensures that workers are saving the models to the same place and not `Path does not exist is raised`.

Therefore what happens when using these callbacks in the cluster? Can we get a print of the directory models are being saved to?


Other than this questions everything looks clean

**Comment by fabiocruz** [comment]
> Since we are inheriting from the `mlflow logger` callback and then writing a lot of new code why not just create our own callback to log the models?
> 
> In other words, what does this gain when compared to something from scratch [like this](https://github.com/inductiva/inductiva-ml-codebase/pull/8).

Agreed, there seems to be repetition here...

@AugustoPeres: would it make sense to use the `MLFlowLogger` that @VictorGillioz uses here in https://github.com/inductiva/inductiva-ml-codebase/pull/8?

**Comment by VictorGillioz** [comment]
In our use case, MLFlowLogger takes care of much of the needed code. It starts and stop the MLFLow run, it logs all the metrics, it also offers a method to log hyperparameters. Overall, it reduces our work to two lines in main.

The reason for the custom classes is that MLFlowLogger does not offer the possibility to save checkpoints to MLFlow (I think this is added in pytorch lightning 2 but we are using 1.6 for compatibility with ray).

However, when providing the lightning trainer with a checkpoint callback, it will call the logger's `after_save_checkpoint` method each time it saves a checkpoint. This allows us to rely on an external checkpoint callback to decide which checkpoints to save, and only take care of the artifacts logging in our custom class.

I would also argue that this does not require a lot of code, the classes are less than 20 lines.

**Comment by AugustoPeres** [comment]
> However, when providing the lightning trainer with a checkpoint callback, it will call the logger's `after_save_checkpoint` 

And when is this happening? Is it every n batches? Is it at the end of each epoch?

**Comment by VictorGillioz** [comment]
It is called each time the checkpoint callback saves a checkpoint. I guess it then depends on the checkpoint callback you use .

You can find the method call in the documentation [here](https://lightning.ai/docs/pytorch/1.6.0/_modules/pytorch_lightning/callbacks/model_checkpoint.html#ModelCheckpoint) at the end of the method `_save_checkpoint`. You can search for `# notify loggers`.

**Pull request merged**
